# configs/train_configs/intra/3LGGI_PhysMamba.yaml
BASE: ['']
TOOLBOX_MODE: "train_and_test"

TRAIN:
  BATCH_SIZE: 16
  EPOCHS: 30
  LR: 3e-4
  MODEL_FILE_NAME: LGGI_LGGI_LGGI_PhysMamba
  AUG: 1
  DATA:
    FS: 30
    DATASET: LGGI
    DO_PREPROCESS: True
    DATA_FORMAT: NDCHW
    RAW_DATA_PATH: ./rppg_dataset/LGGI/
    CACHED_PATH: ./rppg_dataset/LGGI_inter/
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.6
    PREPROCESS:
      DATA_TYPE: ['Standardized']
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      DATA_AUG: ['None']
      USE_PSEUDO_PPG_LABEL: False
      CROP_FACE:
        DO_CROP_FACE: True
        METHOD: 'r2i_facemesh'
        USE_ADAPTIVE_ROI: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 128
        W: 128

VALID:
  DATA:
    FS: 30
    DATASET: LGGI
    DO_PREPROCESS: True
    DATA_FORMAT: NDCHW
    RAW_DATA_PATH: ./rppg_dataset/LGGI/
    CACHED_PATH: ./rppg_dataset/LGGI_inter/
    EXP_DATA_NAME: ""
    BEGIN: 0.6
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Standardized']
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      DATA_AUG: ['None']
      USE_PSEUDO_PPG_LABEL: False
      CROP_FACE:
        DO_CROP_FACE: True
        METHOD: 'r2i_facemesh'
        USE_ADAPTIVE_ROI: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 128
        W: 128

TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson','SNR','BA']
  USE_LAST_EPOCH: False
  DATA:
    FS: 30
    DATASET: LGGI
    DO_PREPROCESS: True
    DATA_FORMAT: NDCHW
    RAW_DATA_PATH: ./rppg_dataset/LGGI/
    CACHED_PATH: ./rppg_dataset/LGGI_inter/
    EXP_DATA_NAME: ""
    BEGIN: 0.6
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Standardized']
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      DATA_AUG: ['None']
      USE_PSEUDO_PPG_LABEL: False
      CROP_FACE:
        DO_CROP_FACE: True
        METHOD: 'r2i_facemesh'
        USE_ADAPTIVE_ROI: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 128
        W: 128

DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp/LGGI
MODEL:
  DROP_RATE: 0.2
  NAME: PhysMamba
  MODEL_DIR: ./output/LGGI_LGGI_PhysMamba
INFERENCE:
  BATCH_SIZE: 16
  EVALUATION_METHOD: "FFT"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False
    WINDOW_SIZE: 10
  MODEL_PATH: ''
